#
# Copyright (c) 2019-2026 0xACE8
#
# 本ソフトウェアはフリーソフトウェアであり、MITライセンスの下で公開されています。
# 詳細については /LICENSE を参照してください。
#
# https://github.com/0xACE8
#
# 説明: GitHub Actionsのモジュール化を活用し、プライバシーとセキュリティを確保したOpenWrtビルド。
#

name: Build virtual_machines_x64 imwrt 25.12-snapshot kernel 6.12 actions.

on:
  workflow_dispatch:
    inputs:
      restore_config:
        description: 'Restore Configuration. 🇯🇵 設定を復元'
        type: boolean
        default: false
      #boost_wifi_5g:
      #  description: 'Boost Wi-Fi 5G Signal. 🇯🇵 5G信号の増幅'
      #  type: boolean
      #  default: false
      upload_firmware:
        description: 'Upload FW to Artifact. 🇯🇵 Artifactに保存'
        type: boolean
        default: false
      upload_release:
        description: 'Upload FW to Release.. 🇯🇵 Releaseに公開'
        type: boolean
        default: false
      #upload_wenshushu:
      #  description: 'Upload FW to WENSHUSHU 🇯🇵 文叔叔に転送'
      #  type: boolean
      #  default: false
      telegram_notify:
        description: 'Telegram Notification. 🇯🇵 Telegram通知'
        type: boolean
        default: true
      keepalive_cache:
        description: 'Manual Cache Keepalive 🇯🇵 保活モード'
        type: boolean
        default: false
  schedule:
    - cron: '0 2 * * 1'
    - cron: '0 0 1 * *'
    
env:
  # git repo url
  GIT_REPO_URL:         ${{ secrets.IMMORTALWRT_SOURCE_LINK }}
  GIT_TREE_REF:         ${{ secrets.IMMORTALWRT_SOURCE_TREE }}
  GIT_HEAD_REF:         ${{ secrets.IMMORTALWRT_2512SS_HEAD }}
  PRIVATE_DATA:         ${{ secrets.SOLIDWRT_DATA }}
  # github token
  GITHUB_TOKEN:         ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN:         ${{ secrets.ACCESS_TOKEN }}
  # free disk space
  EXPAND_SPACE:         ${{ secrets.FREE_DISKS_SPACE }}
  # feeds source & check sha512sum
  FEEDS_SOURCE:         ${{ secrets.ADD_FEEDS_OP2512 }}
  CHECK_SHA512:         ${{ secrets.CHECK_SHA512SUMS }}
  REPACK_IMAGE:         ${{ secrets.REPACKAGE_IMAGES }}
  # luci & packages repo
  PLUGINS_REPO:         ${{ secrets.PLUGINS_REPO_ACE }}
  PLUGINS_HEAD:         ${{ secrets.PLUGINS_2512_ACE }}
  PLUGINS_SYNC:         ${{ secrets.PLUGINS_SYNC_ACE }}
  # telegram bot
  TGRAM_BOTKEY:         ${{ secrets.TELEGRAM_BOT_KEY }}
  TGRAM_CHATID:         ${{ secrets.TELEGRAM_CHAT_ID }}
  TGRAM_DONEID:         ${{ secrets.TELEGRAM_DONE_ID }}
  # input status
  INPUT_CONFIG:         ${{ github.event.inputs.restore_config }}
  INPUT_WIFI5G:         ${{ github.event.inputs.boost_wifi_5g }}
  INPUT_UP_ART:         ${{ github.event.inputs.upload_firmware }}
  INPUT_UP_REL:         ${{ github.event.inputs.upload_release }}
  INPUT_UP_WSS:         ${{ github.event.inputs.upload_wenshushu }}
  INPUT_NOTIFY:         ${{ github.event.inputs.telegram_notify }}
  INPUT_KALIVE:         ${{ github.event_name == 'schedule' || github.event.inputs.keepalive_cache == 'true' }}
  # hardware & repo info
  TARGET_MODEL:         virtual_machines_x64
  TARGET_CHIPS:         x86_64
  TARGET_MEDIA:         8g_ssd
  CODE_SOURCES:         immortalwrt
  LINUX_KERNEL:         kernel_6.12
  OUTPUT_FILES:         solidwrt-25.12ss-virtual_machines_x64-8gb_ssd-sysupgrade
  TZ: "Asia/Tokyo"

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions: write-all

    steps:
    - name: Start Timer (計測開始)
      run: |
        echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

    - name: Sync and Wait for Plugin Repo (プラグインリポジトリの同期と待機)
      run: |
        LAST_TS=$(date -d $(gh run list -w "$PLUGINS_SYNC" -R "$PLUGINS_REPO" -s success --limit 1 --json updatedAt -q '.[0].updatedAt // "1970-01-01"') +%s)
        DIFF=$(( ($(date +%s) - LAST_TS) / 3600 ))
        if [ "$DIFF" -ge 24 ]; then
          echo "⚠️ 最終同期から ${DIFF}時間経過。同期を開始します..."
          gh workflow run "$PLUGINS_SYNC" -R "$PLUGINS_REPO" -r "$PLUGINS_HEAD"
          for i in {1..30}; do
            sleep 20
            RUN_ID=$(gh run list -w "$PLUGINS_SYNC" -R "$PLUGINS_REPO" --limit 1 --json databaseId,status -q 'map(select(.status != "completed")) | .[0].databaseId')
            [[ -n "$RUN_ID" && "$RUN_ID" != "null" ]] && break
          done
          [[ -z "$RUN_ID" ]] && echo "❌ Timeout" && exit 1
          gh run watch "$RUN_ID" -R "$PLUGINS_REPO" --exit-status
        else
          echo "✅ 最近同期されました（${DIFF}時間前）。スキップします。"
        fi

    - name: Checkout Repo A (チェックアウト)
      uses: actions/checkout@main

    - name: Check Server Performance (サーバー性能の確認)
      id: check_env
      run: |
        CPU_MODEL=$(cat /proc/cpuinfo | grep -m1 "model name" | awk -F: '{print $2}' | sed 's/^[ \t]*//')
        FREE_SPACE=$(df --block-size=1G / | awk 'NR==2 {print $4}')
        echo "⚠️注意⚠️"
        echo "サーバーのリソースは有限です。プラグインの過剰な選択はCPU高負荷の原因となります。"
        echo -e "既知のCPUモデル（降顺）: 9V74, 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "-------------------------CPU 情報---------------------------"
        echo "CPUの物理数  : $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPUコア数    : $(nproc)"
        echo -e "CPUモデル情報: $CPU_MODEL\n"
        echo "------------------------メモリ情報--------------------------"
        echo "メモリの詳細:"
        free -h
        echo ""
        echo "---------------------ハードディスク情報---------------------"
        # 兼容更多磁盘命名方式
        echo "ディスクデバイス数: $(lsblk -dn -o NAME | grep -E '^sd|^vd|^nvme' | wc -l)"
        df -hT
        echo ""
        echo "------------------サーバー最適化の実行結果------------------"
        if [[ "$CPU_MODEL" != *"EPYC 7763"* && "$CPU_MODEL" != *"EPYC 9V74"* ]]; then
          echo "❌ ハードウェア不適合、ジョブを停止します。"
          gh workflow run "${{ github.workflow }}" --ref "${{ github.ref_name }}"
          sleep 15
          gh run cancel ${{ github.run_id }}
          sleep 10
          exit 1
        fi

    - name: Delete Old Workflows (古いワークフローの削除)
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ env.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
        delete_workflow_pattern: "imwrt 25.12ss kernel 6.12"

    - name: Free Disk Space (ディスク空き容量の確保)
      run: |
        ${{ env.EXPAND_SPACE }}
        sudo mkdir -p /build
        sudo mount /dev/github/runner /build
        sudo chown -R runner:runner /build
        sudo ln -s /build $GITHUB_WORKSPACE/openwrt
        df -Th
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: Checkout Repo B (Data)
      uses: actions/checkout@main
      with:
        repository: ${{ env.PRIVATE_DATA }}
        token: ${{ env.GITHUB_TOKEN }}
        path: 'private_data'

    - name: Set Variables
      run: |
        ls
        # git repo patch
        echo "SOURCE_PATCH=private_data/devices/virtual_machines_x64/repo/patch/immortalwrt-2512ss-patch.sh" >> $GITHUB_ENV
        # device files
        echo "DEVICE_PATCH=private_data/devices/virtual_machines_x64/patch/device_patch.sh" >> $GITHUB_ENV
        echo "BUILD_CONFIG=private_data/devices/virtual_machines_x64/config/.config" >> $GITHUB_ENV
        echo "BACKUP_FILES=private_data/devices/virtual_machines_x64/archive/immortalwrt-25.12/" >> $GITHUB_ENV
        # cmcc color sytle for argon
        echo "ARGON_COLORS=private_data/devices/virtual_machines_x64/theme/argon_theme.sh" >> $GITHUB_ENV

    - name: Initialization environment  (環境の初期化)
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi -f $(docker images -q) 2>/dev/null || true
        [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
        sudo swapoff -a
        sudo rm -f /swapfile /mnt/swapfile
        sudo -E apt-get -y update
        sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
        sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-make-openwrt-depends)
        sudo -E apt-get -y install dos2unix python3-netifaces libfuse-dev
        sudo -E systemctl daemon-reload
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
        sudo rm -rf ~/.dotnet
        sudo -E timedatectl set-timezone "$TZ"
        sudo -E ntpdate ntp.ubuntu.com 0.pool.ntp.org || true
        sudo -E timedatectl set-ntp true
        date -u
        timedatectl status || true
        echo "status=success" >> ${GITHUB_OUTPUT}
        git config --global url."https://$ACCESS_TOKEN@github.com/0xACE8/".insteadOf "https://github.com/0xACE8/"
        git config --global core.compression 0
