#
# Copyright (c) 2019-2026 0xACE8
#
# 本ソフトウェアはフリーソフトウェアであり、MITライセンスの下で公開されています。
# 詳細については /LICENSE を参照してください。
#
# https://github.com/0xACE8
#
# 説明: GitHub Actionsのモジュール化を活用し、プライバシーとセキュリティを確保したOpenWrtビルド。
#

name: Build virtual_machines_x64 imwrt 25.12-snapshot kernel 6.12 actions.

on:
  workflow_dispatch:
    inputs:
      restore_config:
        description: 'Restore Configuration. 🇯🇵 設定を復元'
        type: boolean
        default: false
      #boost_wifi_5g:
      #  description: 'Boost Wi-Fi 5G Signal. 🇯🇵 5G信号の増幅'
      #  type: boolean
      #  default: false
      upload_firmware:
        description: 'Upload FW to Artifact. 🇯🇵 Artifactに保存'
        type: boolean
        default: false
      upload_release:
        description: 'Upload FW to Release.. 🇯🇵 Releaseに公開'
        type: boolean
        default: false
      #upload_wenshushu:
      #  description: 'Upload FW to WENSHUSHU 🇯🇵 文叔叔に転送'
      #  type: boolean
      #  default: false
      telegram_notify:
        description: 'Telegram Notification. 🇯🇵 Telegram通知'
        type: boolean
        default: true
      keepalive_cache:
        description: 'Manual Cache Keepalive 🇯🇵 保活モード'
        type: boolean
        default: false
  schedule:
    - cron: '0 2 * * 1'
    - cron: '0 0 1 * *'
    
env:
  ## github token
  GITHUB_TOKEN:         ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN:         ${{ secrets.ACCESS_TOKEN }}
  RUN_WORKFLOW:         ${{ github.workflow }}
  RUN_REF_NAME:         ${{ github.ref_name }}
  RUN_REF_REPO:         ${{ github.repository }}
  RUNID_NUMBER:         ${{ github.run_id }}
  ## solidwrt core
  PRIVATE_DATA:         ${{ secrets.SOLIDWRT_CORE }}
  ## github ci
  PLUGINS_2512:         ${{ github.workspace }}/${{ secrets.PLUGINS_2512_ACE }}
  PLUGINS_2410:         ${{ github.workspace }}/${{ secrets.PLUGINS_2410_ACE }}
  CHECK_SERVER:         ${{ github.workspace }}/${{ secrets.TEST_SERVER_PERF }}
  INIT_ENV_VAR:         ${{ github.workspace }}/${{ secrets.INIT_ENVIRONMENT }}
  EXPAND_SPACE:         ${{ github.workspace }}/${{ secrets.FREE_DISKS_SPACE }}
  CLONE_IM2512:         ${{ github.workspace }}/${{ secrets.CLONE_IM2512_SRC }}
  CLONE_IM2410:         ${{ github.workspace }}/${{ secrets.CLONE_IM2512_SRC }}
  PATCH_IM2512:         ${{ github.workspace }}/${{ secrets.SRC_PATCH_IM2512 }}
  PATCH_IM2410:         ${{ github.workspace }}/${{ secrets.SRC_PATCH_IM2410 }}
  FEEDS_OP2512:         ${{ github.workspace }}/${{ secrets.ADD_FEEDS_OP2512 }}
  FEEDS_OP2410:         ${{ github.workspace }}/${{ secrets.ADD_FEEDS_OP2410 }}
  DEVICE_PATCH:         ${{ github.workspace }}/${{ secrets.DEVICE_DIFFPATCH }}
  BUILD_CONFIG:         ${{ github.workspace }}/${{ secrets.BUILD_DIFFCONFIG }}
  BACKUP_FILES:         ${{ github.workspace }}/${{ secrets.BACKUP_CONFIGURE }}
  ARGON_COLORS:         ${{ github.workspace }}/${{ secrets.ARGON_THEMECOLOR }}
  CHECK_SHA512:         ${{ github.workspace }}/${{ secrets.CHECK_SHA512SUMS }}
  REPACK_IMAGE:         ${{ github.workspace }}/${{ secrets.REPACKAGE_IMAGES }}
  ## telegram bot
  TGRAM_BOTKEY:         ${{ secrets.TELEGRAM_BOT_KEY }}
  TGRAM_CHATID:         ${{ secrets.TELEGRAM_CHAT_ID }}
  TGRAM_DONEID:         ${{ secrets.TELEGRAM_DONE_ID }}
  ## input status
  INPUT_CONFIG:         ${{ github.event.inputs.restore_config }}
  INPUT_WIFI5G:         ${{ github.event.inputs.boost_wifi_5g }}
  INPUT_UP_ART:         ${{ github.event.inputs.upload_firmware }}
  INPUT_UP_REL:         ${{ github.event.inputs.upload_release }}
  INPUT_UP_WSS:         ${{ github.event.inputs.upload_wenshushu }}
  INPUT_NOTIFY:         ${{ github.event.inputs.telegram_notify }}
  INPUT_KALIVE:         ${{ github.event_name == 'schedule' || github.event.inputs.keepalive_cache == 'true' }}
  ## hardware & repo info
  TARGET_MODEL:         virtual_machines_x64
  TARGET_CHIPS:         x86_64
  TARGET_MEDIA:         8g_ssd
  LINUX_KERNEL:         kernel_6.12
  OUTPUT_FILES:         solidwrt-25.12ss-virtual_machines_x64-8gb_ssd
  TZ: "Asia/Tokyo"

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions: write-all

    steps:
    - name: Start Timer (計測開始)
      run: |
        echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

    - name: Checkout Repo A (チェックアウト)
      uses: actions/checkout@main

    - name: Checkout Repo B (Data)
      uses: actions/checkout@main
      with:
        repository: ${{ env.PRIVATE_DATA }}
        token: ${{ env.GITHUB_TOKEN }}
        path: 'private_data'

    - name: Delete Old Workflows (古いワークフローの削除)
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ env.ACCESS_TOKEN }}
        repository: ${{ env.RUN_REF_REPO }}
        retain_days: 0
        keep_minimum_runs: 0
        delete_workflow_pattern: "imwrt 25.12-snapshot kernel 6.12"

    - name: Check Server Performance (サーバー性能の確認)
      id: check_env
      run: |
        ${{ env.CHECK_SERVER }}

    - name: Sync and Wait for Plugin Repo (プラグインリポジトリの同期と待機)
      run: |
        ${{ env.PLUGINS_2512 }}

    - name: Initialization Environment  (環境の初期化)
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ${{ env.INIT_ENV_VAR }} >/dev/null 2>&1

    - name: Free Disk Space (ディスク空き容量の確保)
      run: |
        ${{ env.EXPAND_SPACE }} >/dev/null 2>&1
        df -Th

    - name: Clone Source Code (ソースコードのクローン)
      working-directory: ./
      run: |
        ${{ env.CLONE_IM2512 }}
        ${{ env.FEEDS_OP2512 }}

    - name: Update & Install Feeds (フィードの更新とインストール)
      working-directory: ./openwrt
      run: |
        ${{ env.DEVICE_PATCH }}
        # rtl88x2bu support
        git clone -b openwrt-25.12.0-rc4 https://github.com/mirobiala/rtl88x2bu-cl package/kernel/rtl88x2bu-cl
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration (カスタム設定の読み込み)
      working-directory: ./openwrt
      id: loadconfig
      run: |
        cp -rf ${{ env.BUILD_CONFIG }} .config
        ${{ env.PATCH_IM2512 }}
        ${{ env.ARGON_COLORS }}

    - name: Restore Config Archive (設定アーカイブの復元)
      if: steps.loadconfig.outcome == 'success' && env.INPUT_RESTORE == 'true'
      working-directory: ./openwrt
      run: |
        mv ${{ env.BACKUP_FILES }} files
        ls files
        echo "OUTPUT_FILE=$OUTPUT_FILES-configured" >> $GITHUB_ENV
